version: '3.8'

services:
  # spark-master:
  #   image: bitnami/spark:3.4.1
  #   container_name: spark-master
  #   environment:
  #     - SPARK_MODE=master
  #     - SPARK_RPC_AUTHENTICATION_ENABLED=no
  #     - SPARK_RPC_ENCRYPTION_ENABLED=no
  #     - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
  #     - SPARK_SSL_ENABLED=no
  #   ports:
  #     - "7077:7077"
  #     - "8080:8080"
  #   networks:
  #     - bigdata-net

  # spark-worker:
  #   image: bitnami/spark:3.4.1
  #   container_name: spark-worker
  #   environment:
  #     - SPARK_MODE=worker
  #     - SPARK_MASTER_URL=spark://spark-master:7077
  #     - SPARK_WORKER_MEMORY=8G
  #     - SPARK_WORKER_CORES=4
  #   depends_on:
  #     - spark-master
  #   ports:
  #     - "8081:8081"
  #   networks:
  #     - bigdata-net

  # jupyter:
  #   image: jupyter/pyspark-notebook:python-3.10
  #   container_name: jupyter
  #   environment:
  #     - JUPYTER_ENABLE_LAB=yes
  #     - GRANT_SUDO=yes
  #   ports:
  #     - "8888:8888"
  #   volumes:
  #     - ./:/home/jovyan/work
  #   networks:
  #     - bigdata-net
  #   depends_on:
  #     - spark-master
  #     - spark-worker

  influxdb:
    image: influxdb:2.7
    container_name: influxdb
    ports:
      - "8086:8086"
    volumes:
      - influxdb-data:/var/lib/influxdb2
    networks:
      - bigdata-net

  grafana:
    image: grafana/grafana:9.5.2
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana-data:/var/lib/grafana
    networks:
      - bigdata-net
    depends_on:
      - influxdb

# (Optionnel) HDFS local, décommenter si besoin
#  hadoop:
#    image: bde2020/hadoop-namenode:2.0.0-hadoop3.2.1-java8
#    container_name: hadoop-namenode
#    environment:
#      - CLUSTER_NAME=bigdata-cluster
#    ports:
#      - "9870:9870"
#    volumes:
#      - hadoop-data:/hadoop/dfs/name
#    networks:
#      - bigdata-net

volumes:
  influxdb-data:
  grafana-data:
#  hadoop-data:

networks:
  bigdata-net:
    driver: bridge
